Console.WriteLine("Ceza mı bu");
Console.WriteLine("Çektiğim çile mi");
Console.WriteLine("Yıllardır tuttuğum nöbet bitmeyecek mi?");
Console.WriteLine("Bir küçük kar tanesi gibiyim");
Console.WriteLine("Avucunda eriyen dön bebeğim");
Console.WriteLine();
Console.WriteLine("Gözyaşlarını görürsem");
Console.WriteLine("Erir kanatlarım");
Console.WriteLine("Uçamam rüyalarında yanına");
Console.WriteLine("Sonsuzluk senle başladı");
Console.WriteLine("O küçük dünyamda");
Console.WriteLine("Unutma gittiğinde yarım kaldım");
Console.WriteLine();
Console.WriteLine("Çöllerdeyim yanıyorum");
Console.WriteLine("Kutuptayım üşüyorum");
Console.WriteLine("Ceza benim çekiyorum ne olur dön");
Console.WriteLine("Uzanıyorum tutamıyorum");
Console.WriteLine("Özlüyorum ağlıyorum");
Console.WriteLine("Yasak mısın anlamıyorum ne olur dön");
Console.WriteLine();
Console.WriteLine("Sevmesen de beni özledim sesini");
Console.WriteLine("Git desem de yine gitmesen");
Console.WriteLine("Yıllardır çektiğim bu hasret mi çile mi?");
Console.WriteLine("Haram mısın bana bi' bilsem");
Console.WriteLine();
Console.WriteLine("Sevmesen de beni özledim sesini");
Console.WriteLine("Git desem de yine gitmesen");
Console.WriteLine("Yıllardır çektiğim bu hasret mi çile mi?");
Console.WriteLine("Haram mısın bana bi' bilsem");
Console.WriteLine();
Console.WriteLine("Bebeğim benim, hayalet sevgilim");
Console.WriteLine("Bebeğim benim, hayalet sevgilim");
Console.WriteLine();
Console.WriteLine("Hayalet sevgilim");
Console.WriteLine();
Console.WriteLine("Çöllerdeyim yanıyorum");
Console.WriteLine("Kutuptayım üşüyorum");
Console.WriteLine("Ceza benim çekiyorum ne olur dön");
Console.WriteLine("Uzanıyorum tutamıyorum");
Console.WriteLine("Özlüyorum ağlıyorum");
Console.WriteLine("Yasak mısın anlamıyorum ne olur dön");
Console.WriteLine();
Console.WriteLine("Sevmesen de beni özledim sesini");
Console.WriteLine("Git desem de yine gitmesen");
Console.WriteLine("Yıllardır çektiğim bu hasret mi çile mi?");
Console.WriteLine("Haram mısın bana bi' bilsem");
Console.WriteLine();
Console.WriteLine("Sevmesen de beni özledim sesini");
Console.WriteLine("Git desem de yine gitmesen");
Console.WriteLine("Yıllardır çektiğim bu hasret mi çile mi?");
Console.WriteLine("Haram mısın bana bi' bilsem");
Console.WriteLine();
Console.WriteLine("Bebeğim benim hayalet sevgilim");
Console.WriteLine("Bebeğim benim hayalet sevgilim");
Console.WriteLine();
Console.WriteLine("Hayalet sevgilim");
Console.WriteLine("Hayalet sevgilim");