    disp("Ceza mı bu");
    disp("Çektiğim çile mi");
    disp("Yıllardır tuttuğum nöbet bitmeyecek mi?");
    disp("Bir küçük kar tanesi gibiyim");
    disp("Avucunda eriyen dön bebeğim");
    disp(" ");
    disp("Gözyaşlarını görürsem");
    disp("Erir kanatlarım");
    disp("Uçamam rüyalarında yanına");
    disp("Sonsuzluk senle başladı");
    disp("O küçük dünyamda");
    disp("Unutma gittiğinde yarım kaldım");
    disp(" ");
    disp("Çöllerdeyim yanıyorum");
    disp("Kutuptayım üşüyorum");
    disp("Ceza benim çekiyorum ne olur dön");
    disp("Uzanıyorum tutamıyorum");
    disp("Özlüyorum ağlıyorum");
    disp("Yasak mısın anlamıyorum ne olur dön");
    disp(" ");
    disp("Sevmesen de beni özledim sesini");
    disp("Git desem de yine gitmesen");
    disp("Yıllardır çektiğim bu hasret mi çile mi?");
    disp("Haram mısın bana bi' bilsem");
    disp(" ");
    disp("Sevmesen de beni özledim sesini");
    disp("Git desem de yine gitmesen");
    disp("Yıllardır çektiğim bu hasret mi çile mi?");
    disp("Haram mısın bana bi' bilsem");
    disp(" ");
    disp("Bebeğim benim, hayalet sevgilim");
    disp("Bebeğim benim, hayalet sevgilim");
    disp(" ");
    disp("Hayalet sevgilim");
    disp(" ");
    disp("Çöllerdeyim yanıyorum");
    disp("Kutuptayım üşüyorum");
    disp("Ceza benim çekiyorum ne olur dön");
    disp("Uzanıyorum tutamıyorum");
    disp("Özlüyorum ağlıyorum");
    disp("Yasak mısın anlamıyorum ne olur dön");
    disp(" ");
    disp("Sevmesen de beni özledim sesini");
    disp("Git desem de yine gitmesen");
    disp("Yıllardır çektiğim bu hasret mi çile mi?");
    disp("Haram mısın bana bi' bilsem");
    disp(" ");
    disp("Sevmesen de beni özledim sesini");
    disp("Git desem de yine gitmesen");
    disp("Yıllardır çektiğim bu hasret mi çile mi?");
    disp("Haram mısın bana bi' bilsem");
    disp(" ");
    disp("Bebeğim benim, hayalet sevgilim");
    disp("Bebeğim benim, hayalet sevgilim");
    disp(" ");
    disp("Hayalet sevgilim");
    disp("Hayalet sevgilim");